---
name: Trivy Java DB
on:
  schedule:
    - cron: "0 0 * * *" # update indexes every day in 00:00
  workflow_dispatch:
env:
  GH_USER: aqua-bot
  DB_VERSION: 1
permissions:
  packages: write # for GHCR
  contents: read
jobs:
  build:
    name: Build DB
    runs-on: ubuntu-latest
    steps:
      - name: GH repo to lower case # `oras push` fails if repository contains uppercase characters
        id: github-repo-lower-case
        run: |
          echo "lowercase_repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Check repo name
        run: echo ${{ steps.github-repo-lower-case.outputs.lowercase_repo }}